LOCAL_PATH:= $(call my-dir)

include $(CLEAR_VARS)

LOCAL_MODULE := librtsp

LOCAL_SRC_FILES := \
	../../../src/BasicUsageEnvironment/BasicHashTable.cpp \
	../../../src/BasicUsageEnvironment/BasicTaskScheduler.cpp \
	../../../src/BasicUsageEnvironment/BasicTaskScheduler0.cpp \
	../../../src/BasicUsageEnvironment/BasicUsageEnvironment.cpp \
	../../../src/BasicUsageEnvironment/BasicUsageEnvironment0.cpp \
	../../../src/BasicUsageEnvironment/DelayQueue.cpp \
	../../../src/UsageEnvironment/HashTable.cpp \
	../../../src/UsageEnvironment/strDup.cpp \
	../../../src/UsageEnvironment/UsageEnvironment.cpp \
	../../../src/groupsock/GroupEId.cpp \
	../../../src/groupsock/Groupsock.cpp \
	../../../src/groupsock/GroupsockHelper.cpp \
	../../../src/groupsock/inet.c \
	../../../src/groupsock/IOHandlers.cpp \
	../../../src/groupsock/NetAddress.cpp \
	../../../src/groupsock/NetInterface.cpp \
	../../../src/liveMedia/AC3AudioFileServerMediaSubsession.cpp \
	../../../src/liveMedia/AC3AudioRTPSink.cpp \
	../../../src/liveMedia/AC3AudioRTPSource.cpp \
	../../../src/liveMedia/AC3AudioStreamFramer.cpp \
	../../../src/liveMedia/ADTSAudioFileServerMediaSubsession.cpp \
	../../../src/liveMedia/ADTSAudioFileSource.cpp \
	../../../src/liveMedia/AMRAudioFileServerMediaSubsession.cpp \
	../../../src/liveMedia/AMRAudioFileSink.cpp \
	../../../src/liveMedia/AMRAudioFileSource.cpp \
	../../../src/liveMedia/AMRAudioRTPSink.cpp \
	../../../src/liveMedia/AMRAudioRTPSource.cpp \
	../../../src/liveMedia/AMRAudioSource.cpp \
	../../../src/liveMedia/AudioInputDevice.cpp \
	../../../src/liveMedia/AudioRTPSink.cpp \
	../../../src/liveMedia/AVIFileSink.cpp \
	../../../src/liveMedia/Base64.cpp \
	../../../src/liveMedia/BasicUDPSink.cpp \
	../../../src/liveMedia/BasicUDPSource.cpp \
	../../../src/liveMedia/BitVector.cpp \
	../../../src/liveMedia/ByteStreamFileSource.cpp \
	../../../src/liveMedia/ByteStreamMemoryBufferSource.cpp \
	../../../src/liveMedia/ByteStreamMultiFileSource.cpp \
	../../../src/liveMedia/DeviceSource.cpp \
	../../../src/liveMedia/DigestAuthentication.cpp \
	../../../src/liveMedia/DVVideoFileServerMediaSubsession.cpp \
	../../../src/liveMedia/DVVideoRTPSink.cpp \
	../../../src/liveMedia/DVVideoRTPSource.cpp \
	../../../src/liveMedia/DVVideoStreamFramer.cpp \
	../../../src/liveMedia/EBMLNumber.cpp \
	../../../src/liveMedia/FileServerMediaSubsession.cpp \
	../../../src/liveMedia/FileSink.cpp \
	../../../src/liveMedia/FramedFileSource.cpp \
	../../../src/liveMedia/FramedFilter.cpp \
	../../../src/liveMedia/FramedSource.cpp \
	../../../src/liveMedia/GenericMediaServer.cpp \
	../../../src/liveMedia/GSMAudioRTPSink.cpp \
	../../../src/liveMedia/H261VideoRTPSource.cpp \
	../../../src/liveMedia/H263plusVideoFileServerMediaSubsession.cpp \
	../../../src/liveMedia/H263plusVideoRTPSink.cpp \
	../../../src/liveMedia/H263plusVideoRTPSource.cpp \
	../../../src/liveMedia/H263plusVideoStreamFramer.cpp \
	../../../src/liveMedia/H263plusVideoStreamParser.cpp \
	../../../src/liveMedia/H264or5VideoFileSink.cpp \
	../../../src/liveMedia/H264or5VideoRTPSink.cpp \
	../../../src/liveMedia/H264or5VideoStreamDiscreteFramer.cpp \
	../../../src/liveMedia/H264or5VideoStreamFramer.cpp \
	../../../src/liveMedia/H264VideoFileServerMediaSubsession.cpp \
	../../../src/liveMedia/H264VideoFileSink.cpp \
	../../../src/liveMedia/H264VideoRTPSink.cpp \
	../../../src/liveMedia/H264VideoRTPSource.cpp \
	../../../src/liveMedia/H264VideoStreamDiscreteFramer.cpp \
	../../../src/liveMedia/H264VideoStreamFramer.cpp \
	../../../src/liveMedia/H265VideoFileServerMediaSubsession.cpp \
	../../../src/liveMedia/H265VideoFileSink.cpp \
	../../../src/liveMedia/H265VideoRTPSink.cpp \
	../../../src/liveMedia/H265VideoRTPSource.cpp \
	../../../src/liveMedia/H265VideoStreamDiscreteFramer.cpp \
	../../../src/liveMedia/H265VideoStreamFramer.cpp \
	../../../src/liveMedia/InputFile.cpp \
	../../../src/liveMedia/JPEGVideoRTPSink.cpp \
	../../../src/liveMedia/JPEGVideoRTPSource.cpp \
	../../../src/liveMedia/JPEGVideoSource.cpp \
	../../../src/liveMedia/Locale.cpp \
	../../../src/liveMedia/MatroskaDemuxedTrack.cpp \
	../../../src/liveMedia/MatroskaFile.cpp \
	../../../src/liveMedia/MatroskaFileParser.cpp \
	../../../src/liveMedia/MatroskaFileServerDemux.cpp \
	../../../src/liveMedia/MatroskaFileServerMediaSubsession.cpp \
	../../../src/liveMedia/Media.cpp \
	../../../src/liveMedia/MediaSession.cpp \
	../../../src/liveMedia/MediaSink.cpp \
	../../../src/liveMedia/MediaSource.cpp \
	../../../src/liveMedia/MP3ADU.cpp \
	../../../src/liveMedia/MP3ADUdescriptor.cpp \
	../../../src/liveMedia/MP3ADUinterleaving.cpp \
	../../../src/liveMedia/MP3ADURTPSink.cpp \
	../../../src/liveMedia/MP3ADURTPSource.cpp \
	../../../src/liveMedia/MP3ADUTranscoder.cpp \
	../../../src/liveMedia/MP3AudioFileServerMediaSubsession.cpp \
	../../../src/liveMedia/MP3AudioMatroskaFileServerMediaSubsession.cpp \
	../../../src/liveMedia/MP3FileSource.cpp \
	../../../src/liveMedia/MP3Internals.cpp \
	../../../src/liveMedia/MP3InternalsHuffman.cpp \
	../../../src/liveMedia/MP3InternalsHuffmanTable.cpp \
	../../../src/liveMedia/MP3StreamState.cpp \
	../../../src/liveMedia/MP3Transcoder.cpp \
	../../../src/liveMedia/MPEG1or2AudioRTPSink.cpp \
	../../../src/liveMedia/MPEG1or2AudioRTPSource.cpp \
	../../../src/liveMedia/MPEG1or2AudioStreamFramer.cpp \
	../../../src/liveMedia/MPEG1or2Demux.cpp \
	../../../src/liveMedia/MPEG1or2DemuxedElementaryStream.cpp \
	../../../src/liveMedia/MPEG1or2DemuxedServerMediaSubsession.cpp \
	../../../src/liveMedia/MPEG1or2FileServerDemux.cpp \
	../../../src/liveMedia/MPEG1or2VideoFileServerMediaSubsession.cpp \
	../../../src/liveMedia/MPEG1or2VideoRTPSink.cpp \
	../../../src/liveMedia/MPEG1or2VideoRTPSource.cpp \
	../../../src/liveMedia/MPEG1or2VideoStreamDiscreteFramer.cpp \
	../../../src/liveMedia/MPEG1or2VideoStreamFramer.cpp \
	../../../src/liveMedia/MPEG2IndexFromTransportStream.cpp \
	../../../src/liveMedia/MPEG2TransportFileServerMediaSubsession.cpp \
	../../../src/liveMedia/MPEG2TransportStreamAccumulator.cpp \
	../../../src/liveMedia/MPEG2TransportStreamFramer.cpp \
	../../../src/liveMedia/MPEG2TransportStreamFromESSource.cpp \
	../../../src/liveMedia/MPEG2TransportStreamFromPESSource.cpp \
	../../../src/liveMedia/MPEG2TransportStreamIndexFile.cpp \
	../../../src/liveMedia/MPEG2TransportStreamMultiplexor.cpp \
	../../../src/liveMedia/MPEG2TransportStreamTrickModeFilter.cpp \
	../../../src/liveMedia/MPEG2TransportUDPServerMediaSubsession.cpp \
	../../../src/liveMedia/MPEG4ESVideoRTPSink.cpp \
	../../../src/liveMedia/MPEG4ESVideoRTPSource.cpp \
	../../../src/liveMedia/MPEG4GenericRTPSink.cpp \
	../../../src/liveMedia/MPEG4GenericRTPSource.cpp \
	../../../src/liveMedia/MPEG4LATMAudioRTPSink.cpp \
	../../../src/liveMedia/MPEG4LATMAudioRTPSource.cpp \
	../../../src/liveMedia/MPEG4VideoFileServerMediaSubsession.cpp \
	../../../src/liveMedia/MPEG4VideoStreamDiscreteFramer.cpp \
	../../../src/liveMedia/MPEG4VideoStreamFramer.cpp \
	../../../src/liveMedia/MPEGVideoStreamFramer.cpp \
	../../../src/liveMedia/MPEGVideoStreamParser.cpp \
	../../../src/liveMedia/MultiFramedRTPSink.cpp \
	../../../src/liveMedia/MultiFramedRTPSource.cpp \
	../../../src/liveMedia/OggDemuxedTrack.cpp \
	../../../src/liveMedia/OggFile.cpp \
	../../../src/liveMedia/OggFileParser.cpp \
	../../../src/liveMedia/OggFileServerDemux.cpp \
	../../../src/liveMedia/OggFileServerMediaSubsession.cpp \
	../../../src/liveMedia/OggFileSink.cpp \
	../../../src/liveMedia/OnDemandServerMediaSubsession.cpp \
	../../../src/liveMedia/ourMD5.cpp \
	../../../src/liveMedia/OutputFile.cpp \
	../../../src/liveMedia/PassiveServerMediaSubsession.cpp \
	../../../src/liveMedia/ProxyServerMediaSession.cpp \
	../../../src/liveMedia/QCELPAudioRTPSource.cpp \
	../../../src/liveMedia/QuickTimeFileSink.cpp \
	../../../src/liveMedia/QuickTimeGenericRTPSource.cpp \
	../../../src/liveMedia/RTCP.cpp \
	../../../src/liveMedia/rtcp_from_spec.c \
	../../../src/liveMedia/RTPInterface.cpp \
	../../../src/liveMedia/RTPSink.cpp \
	../../../src/liveMedia/RTPSource.cpp \
	../../../src/liveMedia/RTSPClient.cpp \
	../../../src/liveMedia/RTSPCommon.cpp \
	../../../src/liveMedia/RTSPRegisterSender.cpp \
	../../../src/liveMedia/RTSPServer.cpp \
	../../../src/liveMedia/RTSPServerRegister.cpp \
	../../../src/liveMedia/RTSPServerSupportingHTTPStreaming.cpp \
	../../../src/liveMedia/ServerMediaSession.cpp \
	../../../src/liveMedia/SimpleRTPSink.cpp \
	../../../src/liveMedia/SimpleRTPSource.cpp \
	../../../src/liveMedia/SIPClient.cpp \
	../../../src/liveMedia/StreamParser.cpp \
	../../../src/liveMedia/StreamReplicator.cpp \
	../../../src/liveMedia/T140TextRTPSink.cpp \
	../../../src/liveMedia/TCPStreamSink.cpp \
	../../../src/liveMedia/TextRTPSink.cpp \
	../../../src/liveMedia/TheoraVideoRTPSink.cpp \
	../../../src/liveMedia/TheoraVideoRTPSource.cpp \
	../../../src/liveMedia/uLawAudioFilter.cpp \
	../../../src/liveMedia/VideoRTPSink.cpp \
	../../../src/liveMedia/VorbisAudioRTPSink.cpp \
	../../../src/liveMedia/VorbisAudioRTPSource.cpp \
	../../../src/liveMedia/VP8VideoRTPSink.cpp \
	../../../src/liveMedia/VP8VideoRTPSource.cpp \
	../../../src/liveMedia/VP9VideoRTPSink.cpp \
	../../../src/liveMedia/VP9VideoRTPSource.cpp \
	../../../src/liveMedia/WAVAudioFileServerMediaSubsession.cpp \
	../../../src/liveMedia/WAVAudioFileSource.cpp \

$(warning =================building src file detail======================)
$(warning $(NDKINC))
$(warning ===============================================================)

LOCAL_C_INCLUDES := \
	$(LOCAL_PATH)/../../../src/UsageEnvironment/include \
	$(LOCAL_PATH)/../../../src/BasicUsageEnvironment/include \
	$(LOCAL_PATH)/../../../src/groupsock/include \
	$(LOCAL_PATH)/../../../src/liveMedia/include \

LOCAL_CPPFLAGS += -fexceptions -DXLOCALE_NOT_USED=1 -DNULL=0 -DNO_SSTREAM=1 -UIP_ADD_SOURCE_MEMBERSHIP -DALLOW_SERVER_PORT_REUSE

include $(BUILD_STATIC_LIBRARY)
